version: '3.9'

services:
  pgdatabase:
    image: postgres:latest
    container_name: questrade-postg-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=questrade
    volumes:
      - "my_questrade_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - questrade-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - questrade-network
volumes:
  my_questrade_data:
    external: true

networks:
  questrade-network:
    driver: bridge
